### ISSUE TITLE
学长有兴趣将repo加入杭电课程分享计划的组织么

### ISSUE THREAD

**Issue by ek1ng** [imba-tjd/HDUHomeWork#8]
https://github.com/HDU-Course
我们希望整合类似的课程分享仓库并且进行长期维护

**Comment by imba-tjd** [comment]
哎呀，之前没看见 :joy:

本仓库没啥机会更新了，我本来也不打算做成全面的，主要是记录我自己学到的内容，顺便分享出来。加进你组织里的readme里就可以了。
